### ISSUE TITLE
Files with .bak extension

### ISSUE THREAD

**Issue by bardware** [ucavalcante/altitude-script-language#6]
Hi,

I have no releation to Altitude Script Language whatsoever.
I'm searching through some files in my project using Visual Studio Code . There are some historic backup files that were renamed to `.bak`. VSCode comes up with the information there are tools available on the Market place that deal with `.bak` files. The only tool I see when searching for `ext:bak` on the Market place is your plugin.
Now, I' curious if `.bak` files have a special meaning in `Altitude` because accordin to all I've seen over the years it's a common extension for any backup file.

Best,
Bernhard

**Comment by ucavalcante** [comment]
.bak files in altitude script language are same file content from extensions ".ags",".irs",".gem",".agm",".irm", but stored a previous version when edit with oficial developer Altitutde tool, in this vscode extension im only read or edit its content when user open it manually.

**Comment by ucavalcante** [comment]
Question Aswered.
